@extends('baselayout.common_page_base')
@section ('content')
 <div class="content">
      <div class="content__padded">
        <div class="terms_content">
          <h3 class="page_title">TERMS OF SERVICE</h3>
          <p>(Effective Date: July 01, 2016)</p>
		  <p class="terms_info">Pegara, Inc. (“Company,” “we”, “us” or “our”) maintains these Terms of Service (“TOS”) that describes the terms and conditions applicable to our various services, features and content, including, without limitation, its brainsalvation™ service (collectively, the “Services”) where this TOS is posted, including, without limitation, (1) our website(s) including at <a class="block__footer__link describe__link" href="https://www.brainsalvation.com" target='_blank'>www.brainsalvation.com</a> (collectively, the “Sites”) and (2) applications and related services and products for mobile or wireless computing devices made available to you in the Service.</p>
		  <p class="terms_info">Your use of the Service is subject at all times to these TOS and the applicable privacy policy (“Privacy Policy”).  Any inconsistencies between this TOS and the Privacy Policy shall be resolved by the Company in its sole and absolute discretion.</p>
          <p class="terms_info">EACH TIME YOU ACCESS OR USE THE SERVICE, YOU AGREE TO BE BOUND BY THESE TOS AND THE PRIVACY POLICY, AND REPRESENT THAT YOU HAVE READ AND UNDERSTAND THE APPLICABLE RIGHTS, OBLIGATIONS, TERMS AND CONDITIONS SET FORTH HEREIN AND THEREIN AND AGREE TO BE LEGALLY BOUND BY THEM.  IF YOU DO NOT UNDERSTAND OR AGREE TO BE BOUND BY (OR CANNOT COMPLY WITH) THESE TOS AND THE PRIVACY POLICY, DO NOT ACCESS OR USE THE SERVICE.  YOUR CONTINUED ACCESS AND USE OF THE SERVICE SHALL BE DEEMED TO CONSTITUTE YOUR AGREEMENT TO BE LEGALLY BOUND BY THESE TOS AND THE PRIVACY POLICY, AS THEY EACH MAY BE AMENDED FROM TIME TO TIME.  ANY REFERENCES HEREIN TO “YOU” AND “YOUR” REFER TO BOTH YOU AND SUCH PERSON AND ENTITY ON WHOSE BEHALF YOU ACT, IF ANY.  YOU SHOULD PRINT A COPY OF OUR TOS FOR FUTURE REFERENCE.</p>
          <p class="terms_info">YOU MAY NOT USE OUR SERVICE IF: (A) YOU CANNOT ENTER INTO A BINDING CONTRACT WITH THE COMPANY; (B) YOU ARE UNDER 18 YEARS OF AGE, IN WHICH CASE YOU MUST NOT CREATE AN ACCOUNT, USE ANY PART OF THE SERVICE, OR SUBMIT PERSONAL INFORMATION THROUGH THE SERVICE OR TO THE COMPANY; (C) YOU ARE NOT ALLOWED TO RECEIVE PRODUCTS, INCLUDING SERVICES OR SOFTWARE, FROM THE UNITED STATES; OR (D) YOU HAVE PREVIOUSLY BEEN BANNED FROM USING THE SERVICE.  </p>
          <p class="terms_info">In some instances, both these TOS and separate terms of service, riders, supplement, amendment, addenda, rules, policies or guidelines set forth additional conditions that may apply to the Service (collectively, the “Additional Terms”).  To the extent there is a conflict between the TOS and any Additional Terms, the Additional Terms will control unless the Company determines otherwise, in its sole and absolute discretion.  The Privacy Policy and Additional Terms (if any) are hereby incorporated into these TOS by this reference.</p>
          <ul class="list__detail">
            <li class="list__detail_item">
              <h4 class="item_title">THE SERVICE</h4>
              <p class="terms_info">(a)	<span class="describe__link">General Description</span>.  Through our Service, we provide assessments, offers, recommendations and information based on health and other personal data received from you. In addition, we may offer certain third party software, technology and other products and services related to the Service.</p>
              <p class="terms_info">(b)	<span class="describe__link">No Medical Advice</span>.  The Site and Service do not include the provision of medical advice by the Company.  The Company does not offer medical advice or diagnoses or engage in the practice of medicine.  Information and materials provided through the Service are solely for informational purposes only and is not intended to be, and do not constitute, a substitute for professional medical advice, diagnosis or treatment.  You should seek the advice of your physician or other qualified medical professional if you have any questions or concerns regarding your medical condition or the use of any medication or medical device.  </p>
              <p class="terms_info">(c)	<span class="describe__link">No Emergency Services</span>.  The Site and Service are for non-emergency purposes only.  If you think you might have a medical emergency, call 911 or your doctor immediately.  The Service is not intended to carry emergency calls of any type, including emergency calls to hospitals, law enforcement agencies, medical care unit or any other kind of emergency service.</p>
              <p class="terms_info">(d)	<span class="describe__link">License to Use Service</span>.  Subject to the terms and conditions of these TOS, the Privacy Policy and any Additional Terms, the Company hereby grants to you a limited, non-exclusive, non-transferable, non-sublicensable and revocable right and license to access and use the Service for your personal and non-commercial purposes.  The Company may terminate this license without notice in the event you fail to comply with these TOS, the Privacy Policy or any Additional Terms.  Upon termination of the license, you must immediately cease accessing and using the Service.</p>
              <p class="terms_info">(e) <span class="describe__link">Limitations</span>.   The license granted to you is subject to the following limitations.  You shall not or permit any other person to:
                <ul>
                  <li class="terms_info">(i)	in whole or in part, (1) modify, translate or create any derivative work of the Service, including any Company Content (defined below) or (2) copy, photocopy, reproduce, translate, disassemble, reverse engineer, decompile, or otherwise attempt to derive source code, underlying ideas, algorithms, structure, or organization of the Service;</li>
                  <li class="terms_info">(ii)	modify, alter or remove any copyright, patent, confidentiality, trademark and other notices, labels or legends displayed in the Service, including in any Company Content;</li>
                  <li class="terms_info">(iii)	sell, grant a security interest in or transfer reproductions of any Company Content or any part thereof for any purposes in any way not expressly authorized herein;</li>
                  <li class="terms_info">(iv)	assign, rent, lease, distribute or license any Company Content or any part of the Service to others; or</li>
                  <li class="terms_info">(v)	exploit the Service, including any Company Content or any of its parts, for any commercial purpose.</li>
                </ul>
              </p>
              <p class="terms_info">
                  <span class="describe__link">You are solely responsible for all of your activity in connection with the Service.  Your failure to comply with the restrictions and limitations listed above and elsewhere in these TOS shall result in termination of the license granted hereunder with immediate effect and may subject you to civil and/or criminal liability.</span>
              </p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">IP OWNERSHIP</h4>
              <p class="terms_info">(a)	<span class="describe__link">Accounts and User Data</span>.  You acknowledge and agree that subject to your rights to User Content (defined below), all rights, title and interest (including all intellectual property rights) in and to the Account and all information and data accumulated in connection with your access and use of the Service (collectively, “User Data”) are and shall be owned solely and exclusively by the Company.  No rights conferred to you in connection with the Service (including any Company Content) may be transferred or assigned by you (by operation of law or otherwise including at the time of cancellation of your Account) to any third party without the prior written consent of the Company.  </p>
              <p class="terms_info">(b)	<span class="describe__link">Company Content</span>.  The Company, its licensors and/or certain third parties (as applicable) retain exclusive right, title and interest (including all intellectual property rights) in and to all materials that are part of the Service (including past, present and future versions) (excluding User Content), including, without limitation: art, icons, graphics, layout, text, images, audio and/or video, designs, features, advertisements, logos, domain names, trade names and marks, and service marks, any and all copyrightable material, the “look and feel”, the compilation, assembly and arrangement of the materials of the Service, and all other materials or content made available in the Service (collectively, “Company Content”) and such Company Content are protected from unauthorized use, copying and dissemination by applicable copyright, trademark, patent, publicity and other laws, rules, regulations and international treaties.  </p>
              <p class="terms_info">(c)	<span class="describe__link">User Content</span>.  Subject to the Company’s exclusive ownership of the Account, User Data and Company Content described above, trademark rights described below and other express ownership right set forth in these TOS, the Privacy Policy and Additional Terms (if any), you retain exclusive right, title and interest in and to your User Content.</p>
              <p class="terms_info">(d)	<span class="describe__link">Trademarks</span>.  All words and logos in the Site and Service marked by the ™ or ® symbols are trademarks and service marks of the Company and/or its licensor(s).  All rights are reserved.  All other trademarks and service marks appearing in the Service are the property of their respective owners.  All rights are reserved.  Use of any of our trademarks, service marks or names as “metatags” for any purpose other than as expressly authorized in these TOS is strictly prohibited. </p>
              <p class="terms_info">(e)	<span class="describe__link">Third Parties Products</span>.  The Service may be incorporated into, and may incorporate itself, software, technology and other products and services owned and controlled by third parties. Any such third party software, technology, and other products  and services that are incorporated in the Service falls under the scope of these TOS. Any and all other third party software, technology and other products and services that may be distributed together with the Service will be subject to you explicitly accepting a license agreement with that third party and/or agreeing to any applicable third party terms and policies.  You acknowledge and agree that you will not enter into a contractual relationship with the Company regarding such third party software, technology  and other products and services and you will look solely to the applicable third party and not to the Company to enforce any of your rights.</p>
              <p class="terms_info">(f)	<span class="describe__link">No Additional Rights</span>.  Only those licenses expressly set forth in these TOS are granted.  No other licenses are granted under these TOS, whether by implication, estoppel, course of conduct, or otherwise.  Nothing in these TOS is intended to transfer any of the right, title and interest (including all intellectual property rights) from the Company and/or its licensors to you or any third party.  If you are ever inadvertently or erroneous held or deemed to be the owner of any such rights, you agree to assign and hereby irrevocably assign to the Company or its licensors, as the case may be, all such rights as of the effective date of these TOS, and agree to execute all documents to implement and confirm the letter and intent of the foregoing. </p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">ACCOUNT, FEES, BILLING METHODS AND TERMINATION</h4>
              <p class="terms_info">(a)	<span class="describe__link">Accounts</span>.  By completing the Service registration process (where available), you may establish a user account (“Account”), obtain a user ID and become a registered member (“User”), and access the Service.   You may, however, access certain parts of the Service without establishing an Account.  To create an Account or gain limited access to the Service without an Account, you must provide such information as may be requested by the Company truthfully and accurately.      As part of the Service, you will receive email and other communications from us relating to your use of the Service.  By disclosing your email and other contact information to us, you agree that we may send you such communications.  You will no longer receive such communications once your Account is terminated or you opt-out of receiving such communications in accordance with the procedures set forth in the Privacy Policy.</p>
              <p class="terms_info">The Company may approve or reject your Account registration application, or otherwise deny access to the Service, for any reason or no reason in its sole and absolute discretion.  All such decisions shall be final and under no circumstance shall Company be obligated to provide any information regarding its decision-making process. </p>
              <p class="terms_info">You are solely responsible for all activity on your Account and for the security of your personal computer and mobile device. You may not reveal your Account password to other users or permit others to access your Account.  All acts performed using your Account (including User Data and User Content) shall be deemed to be your acts.  You shall promptly notify the Company for any changes to your Account information or if such information has been improperly disclosed to a third party.  You shall solely be responsible for any liability that arises from any improper third party disclosure and/or use (including unauthorized third party use) of your Account (including User Data and User Content).  If there is a risk of your Account (including User Data and User Content) being improperly used by a third party, you shall promptly take all reasonable measures to limit such use, including, without limitation by changing your password and notifying the Company.  Under no circumstances shall the Company be liable to you for any loss you incur, including from the loss of your User Data and User Content, from your loss of any Account information (including user name, user ID or password), unauthorized access or use of your Account and/or from harmful or malicious code.</p>
              <p class="terms_info">You acknowledge and agree that you may not transfer your Account information (including User Data and User Content) to a personal device (new, separate or original device after termination of your Account), and under no circumstance shall the Company be obligated to do so.   </p>
              <p class="terms_info">(b)	<span class="describe__link">Fees</span>.  You may create an Account, and access and use the Service without paying any registration or subscription fees.    However, the Company, in its sole and absolute discretion, may, from time to time, modify, amend, or supplement the terms and billing methods relating to fees and charges, and post those changes in the Service.  Such modifications, amendments or supplements shall be effective immediately upon posting in the Service.  If any change is unacceptable to you, your sole remedy is to cancel your Account and cease using the Service.   If applicable, all fees and charges are non-refundable unless expressly provide otherwise in these TOS or pursuant to applicable law.  The Company will not refund issue any written receipts for any fees or charges you pay in connection with the Service.  </p>
              <p class="terms_info">You must procure and provide all equipment, software and other technologies and data access plans necessary to access the Service, including, a personal computer or mobile device suitable to connect with the Service and an Internet connection.  In addition, you hereby acknowledge and agree that you shall solely be responsible for and bear all telecommunication expenses, including, telephone charges, data plans, Internet connection charges and electricity charges, arising out of your access and use of the Service.</p>
              <p class="terms_info">Subject to technical problems and revisions to payment policies which may be instituted by the Company and partners at any time without notice, you may pay for any applicable fees and other charges by major credit card or such other methods expressly authorized in writing by the Company and its partners. </p>
              <p class="terms_info">Any dispute arising between you and any third party payment process service (including a credit card company) shall be resolved directly between you and such third party.  Under no circumstances shall Company be liable for any obligations incurred by you to such third party in connection with your access and use of the Service.  You agree to indemnify, defend and hold harmless any and all Company Affiliates (defined below) from all claims for liabilities, losses and expenses, including reasonable attorneys’ fees, from third parties arising from such disputes. </p>
              <p class="terms_info">(c)	<span class="describe__link">Termination</span>. You have the right to terminate your Account and/or cease accessing and using the Service at any time by following the procedures in the Service. You understand and agree that unless otherwise expressly provided for in this TOS, terminating your Account and ceasing access and use of the Service are your sole right and remedy with respect to any dispute, including, but not limited to, any related to, or arising out of: (i) any term of this TOS, the Privacy Policy and/or any Additional Terms, or the Company’s enforcement or application thereof, (ii) the Company Content, User Data, User Content and other content available through the Service, (iii) your ability to access and/or use the Service and/or (iv) the amount or type of fees, surcharges, applicable taxes, billing methods, or any change to the fees, applicable taxes, surcharges or billing methods.  Upon termination of your Account, you shall promptly pay any and all outstanding and accrued Service fees and charges payable to the Company.</p>
              <p class="terms_info">Without limiting any other remedies, we may suspend or terminate your Account and/or your access to and use of the Service (or any portion thereof, including any User Data and User Content) at any time if you are, or we suspect that you are, failing to comply with any of this TOS, the Privacy Policy and/or Additional Terms with or without notice to you. </p>
              <p class="terms_info">If you terminate your Account or the Company suspends or terminates your Account, or terminates your access and use of the Service, you may lose your user ID, User Data and User Content as well as any benefits, privileges and User Content associated with the Service, and we are under no obligation to compensate you for any such losses or results.  In addition, no online time or other credits will be provided to you or converted to cash or other form of reimbursement, and you will have no further access to the Service (including all User Data and User Content).   Also, you will not have the right to transfer, sell, or assign any User Data to anyone else.  Under no circumstances shall Company be responsible for storing any User Data or User Content and other information following suspension, termination, modification or deletion of your Account and/or access to the Service.  </p>
              <p class="terms_info">We reserve the right to stop offering and/or supporting the Service at any time for any valid commercial reason, at which time your license to access and use the Service will automatically be terminated without further action.  In such event, we shall not be required to provide refunds, benefits or other compensation to you except as otherwise agreed to in writing by the Company or pursuant to applicable law.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">USER CONTENT AND LICENSE</h4>
              <p class="terms_info">The Company does not solicit submissions, creative materials, ideas or suggestions other than those the Company may specifically request.  Any communications or materials you transmit to the Company by e-mail or otherwise, including, without limitation, ranking, data, questions, feedback, comments, ideas, images, writings, music, sounds, audiovisual effects, artwork, design elements, graphics, suggestions, concepts, biographical information, notes or chat or message postings, will be treated as non-confidential and non-proprietary except as otherwise described in the Privacy Policy.  </p>
              <p class="terms_info">As part of the Service, you may participate in blogs, message boards, contests, sweepstakes, voting, forums and other communication functionality (if any) and may also be provided with the opportunity to create, submit (through the Site, Service or third party websites, software, or tools), disclose, share, post, display, transmit, perform, publish, distribute or broadcast content and materials to the Company and/or other users, including, without limitation, live and recorded audio and video feeds, photographs, rankings, scores, text, writings, graphics, comments, feedback, suggestions, works of authorship, Personal Information (as defined in the Privacy Policy) or other material, data and content.  All such information you make available through the Service or otherwise transmit to the Company is referred to herein collectively, excluding Company Materials not created by you, as “User Content”.  You hereby represent and warrant to the Company that your User Content is wholly original and has been created by you and you exclusively own the rights to your User Content, including the right to grant all of the rights and licenses in these TOS without the Company incurring any third party obligations or liability arising out of its exercise of the rights thereto granted herein by you.</p>
              <p class="terms_info">Subject to the terms of these TOS, the Privacy Policy, any Additional Terms and any applicable laws, rules and regulations, you hereby grant to the Company the unrestricted, unconditional, unlimited, worldwide, irrevocable, perpetual, fully-paid and royalty-free right and license to host, use, copy, transfer, distribute, reproduce, disclose, sell, re-sell, sub-license, display, perform, transmit, publish, broadcast, modify, delete, make derivative works from, retitle, reformat, translate, archive, store, cache or otherwise exploit in any manner whatsoever, all or any portion of your User Content, for any purpose whatsoever, including, without limitation, in connection with the Service, in any and all formats; on or through any and all media, software, formula or medium now known or hereafter known; and with any technology or devices now known or hereafter developed and to advertise, market and promote same. </p>
              <p class="terms_info">You further agree that subject to the terms of these TOS, the Privacy Policy, any Additional Terms and any applicable laws, rules and regulations, the Company is free to use any ideas, information, concepts, know-how or techniques contained in any of your User Content, for any purposes whatsoever, including, without limitation, developing, producing, marketing and otherwise exploiting products and/or services using such User Content, and without remuneration to you or anyone else of any kind.  You further perpetually and irrevocably grant the Company the unconditional right to use and exploit your name, persona and likeness included in any User Content and in connection with any User Content, without any obligations or remuneration to you.  Except as prohibited by law, you irrevocably waive any rights of attribution and/or any so-called moral rights you may have in any User Content you submit, even if such User Content is altered or changed in a manner not agreeable to you.</p>
              <p class="terms_info">The  Company has no obligation to monitor or enforce your intellectual property rights to your User Content but has the right to protect and enforce its licensed rights to your User Content, including, without limitation, by bringing and controlling actions in your name and on your behalf (at the Company’s cost and expense, to which you hereby consent and irrevocably appoint the Company as your attorney-in-fact, with the power of substitution and delegations, which appointment is coupled with an interest).  You also agree and understand that the Company is not obligated to use User Content and that you will not receive any additional consideration or compensation for your User Content or for any exploitation thereof.  Should the Company institute any action to protect and enforce its licensed rights as aforesaid, only the Company shall have any claim to any proceeds or awards for damages resulting from such action.</p>
              <p class="terms_info">You acknowledge and agree that your communications with other users via any channel of communication in the Service are public and not private, and that you have no expectation of privacy concerning your access and use of the Service.  You acknowledge that personal information that you communicate in the Service in such fashion may be seen and used by others and result in unsolicited communications, therefore we strongly encourage you not to disclose any personal information about yourself in your public communications in the Service.  You acknowledge and agree that that by using the Service you may be exposed to content that you may find offensive, indecent or objectionable and that you access and use the Service based on such understanding and at your own risk.  You are solely responsible for these communications and their legality under all applicable rules, laws and regulations.  The Company is not responsible for information that you choose to communicate to other users in the Service, or for the actions of other users. </p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">CONDUCT</h4>
              <p class="terms_info">You agree that you will be personally responsible for your access and use of the Service and for all of your User Content and online activity in connection with the Service, and that you will indemnify, defend and hold harmless the Company, its licensors, suppliers, partners, affiliates and their respective employees, officers, directors and agents (collectively, “Company Affiliates”) from all claims for liabilities, losses and expenses, including reasonable attorneys’ fees and costs, from third parties arising from such use, User Content and activity.  Specifically, you agree to comply with these TOS, all applicable laws, rules and regulations governing the disclosure and use of third party property, including, without limitation, any and all intellectual property rights. Moreover, you agree not to engage in any of the following:
                <ul>
                  <li class="terms_info">(a)	Post, transmit, promote, distribute or provide links to illegal content. </li>
                  <li class="terms_info">(b)	Harass, threaten, abuse, disparage, libel, slander, embarrass, or engage in any other disruptive behavior involving another user or any Company Affiliate. </li>
                  <li class="terms_info">(c)	Transmit or facilitate distribution of content that is harmful, abusive, racially or ethnically offensive, vulgar, sexually explicit, defamatory, infringing, invasive of personal privacy or publicity rights, or in a reasonable person's view, objectionable.</li>
                  <li class="terms_info">(d)	Infringe upon the intellectual property rights of the Company or any third party. </li>
                  <li class="terms_info">(e)	Alter, delete or cancel any other user’s profile information or User Content. </li>
                  <li class="terms_info">(f)	Disrupt the flow of chat in chat rooms, forum or other communication areas within the Service with vulgar language, abusiveness, hitting the return key repeatedly or inputting large images so the screen goes by too fast to read, use of excessive shouting, using ALL CAPS in an attempt to disturb other users, “spamming” or flooding or posting repetitive text.</li>
                  <li class="terms_info">(g)	Impersonate another person, indicate that you are a Company Affiliate, or attempt to mislead users by indicating that you represent Company or any Company Affiliate. </li>
                  <li class="terms_info">(h)	Use any robot, spider, scraper, or other automated means (other than in accordance with these TOS and any Additional Terms) to access the Service for any purpose without our express written permission or bypass measures we may use to prevent or restrict access to the Service.</li>
                  <li class="terms_info">(i)	Attempt to get a user ID, password, or other user information, or any other private information from a user. <span class="describe__link">Company employees will NEVER ask for your password.  DO NOT give your password, secret answers, or billing information out to anyone.</span></li>
                  <li class="terms_info">(j)	Upload any content, including User Content that you do not own or have the right to license to the Company in accordance with these TOS. </li>
                  <li class="terms_info">(k)	Engage in or promote or encourage any illegal or fraudulent activity including hacking, cracking or distribution of counterfeit software, or identity theft. </li>
                  <li class="terms_info">(l)	Upload User Content or display URLs that contain harmful or malicious code or corrupted data. </li>
                  <li class="terms_info">(m)	Post messages for any purpose other than personal communication, including, without limitation, advertising, promotional materials, chain letters, direct marketing, multi-level marketing programs and pyramid schemes.</li>
                  <li class="terms_info">(n)	Make any commercial use of the Service, including using the Service as an Internet dating service website, use at a cyber café or any other location-based site.</li>
                  <li class="terms_info">(o)	Improperly use support or complaint buttons or make false reports to Company. </li>
                  <li class="terms_info">(p)	Use or distribute “auto” software programs, “macro” software programs or other “cheat utility” software program or applications.</li>
                  <li class="terms_info">(q)	Modify, reproduce, distribute, delete or create derivative works of the Service, Company Content or any other users’ User Content displayed therein, or any component thereof.</li>
                  <li class="terms_info">(r)	Solicit or attempt to solicit, and post, distribute or communicate any user’s personal information. </li>
                  <li class="terms_info">(s)	Interfere with, hack into or decipher any transmissions to or from the servers running the Service. </li>
                  <li class="terms_info">(t)	Exploit any bug in the Service or in any Company product to exploit it for commercial purposes.  You agree not to communicate the existence of any such bug (either directly or through the public posting) to any other user or third party. </li>
                  <li class="terms_info">(u)	Do anything that interferes with the ability of other users to enjoy the Service or that materially increases the expense or difficulty of Company in maintaining the Service for the enjoyment of all its users. </li>
                  <li class="terms_info">(v)	Interfere or attempt to interfere with the proper functioning of the Service or connect to or use the Service in any way not expressly permitted by this TOS, including, without limitation, gain unauthorized access to any Company Content and other users’ User Content.</li>
                  <li class="terms_info">(w)	Use the Service in violation of these Terms, the Privacy Policy, Additional Terms (if any) or any applicable laws, rules or regulations, or do anything that promotes the violation of any applicable laws, rules or regulations.</li>
                  <li class="terms_info">(x)	Except in strict conformance to these TOS, the Privacy Policy and any Additional Terms, submit, upload, post, display, publish or broadcast User Content: (A) which constitutes Personal Information (as defined in the Privacy Policy), healthcare-related information (including without limitation “protected health information” under the Health Insurance Portability and Accountability Act of 1996) or any consumer financial information (including information governed by the Gramm-Leach-Bliley Act), (B) for which the disclosure, transmission, receipt, storage or use of which is subject to any restrictions under, or may result in any obligation under, any law, rule or regulation; (C) which would reasonably be considered to be sensitive or where the loss or unauthorized use thereof could reasonably be expected to result in any loss, damage or liability to any person or entity. </li>
                  <li class="terms_info">(y)	Engage in any other conduct which the Company, in its sole and absolute discretion, deems to violate these TOS.</li>
                </ul>
              </p>
              <p class="terms_info">If you encounter another user who is violating any of the items described in the Conduct list above, please email us at <a href="mailto:support@pegara.com" class="block__footer__link describe__link">support@pegara.com</a>.</p>
              <p class="terms_info">We reserve the right to remove any User Content form the Site or the Services at any time for any or no reason, including, without limitation, your breach of these Terms.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">CHANGES TO TOS</h4>
              <p class="terms_info">(a)	<span class="describe__link">Terms of Service</span>.  The Company may, from time to time, modify, amend, or supplement these TOS and post those changes on the TOS page.  Such modifications or supplements shall be effective immediately upon posting in the Service. You are responsible for periodically checking the Service for changes to the TOS.  You can determine when the TOS were last revised by referring to the “Effective Date” legend at the top of these TOS.  If you do not agree to be bound by (or cannot comply with) the TOS as modified or supplemented, you should stop using the Site and Service.  Your continued access and use of the Site and Service constitutes your agreement to be bound by the modified TOS.</p>
              <p class="terms_info">(b)	<span class="describe__link">Changes</span>. The Company reserves the exclusive right and may, at any time and without notice and liability to you, modify, replace, supplement, suspend or discontinue (collectively, “Changes”) the Service (or any portion or feature thereof, including, without limitation, any User Data and User Content), whether temporarily or permanently, in whole or in part, for valid commercial reasons and/or as required by applicable law.  Any such Change shall be effective immediately upon notice by posting in the Service or these TOS, or by any other method of notice the Company deems appropriate.  We shall not be required to provide refunds, benefits or other compensation to you for any Changes, including, without limitation, the suspension or discontinuation of the Service.  Any access or use of the Site or Service after such notice of Change, constitutes acceptance by you of such Change.  Temporary interruptions in the availability of the Service may occur from time to time as normal events.  You agree that no Company Affiliate shall be liable to you or any third party for any revision, supplement, suspension, or discontinuation of the Service, and termination of any license.  The Service may include technical inaccuracies, typographical errors or may enable you to access or download harmful or malicious code introduced onto the Internet by third parties. The Service is made available internationally and may contain references to products, programs and services of the Company /or its licensors that are not available in your location. Such references do not imply that the Company or its licensors intend to make available such products, programs or services in your location.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">DISCLAIMER OF WARRANTIES</h4>
              <p class="terms_info">YOU EXPRESSLY AGREE THAT THE USE OF THE SERVICE AND INTERNET IS AT YOUR SOLE RISK.  THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS FOR YOUR USE, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTIBILITY, SATISFACTORY QUALITY, NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. THE COMPANY PROVIDES THE SERVICE ON A COMMERCIALLY REASONABLE BASIS AND DOES NOT GUARANTEE THAT YOU WILL BE ABLE TO ACCESS OR USE THE SERVICE AT TIMES OR LOCATIONS OF YOUR CHOOSING, OR THAT THE COMPANY WILL HAVE ADEQUATE CAPACITY FOR THE SERVICE AS A WHOLE OR IN ANY SPECIFIC GEOGRAPHIC AREA.  YOUR ACCESS AND USE OF THE SERVICE IS AT YOUR OWN DISCRETION AND RISK AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER OR MOBILE DEVICE, LOSS OF DATA OR ANY OTHER DAMAGES OR LOSSES THAT RESULTS (DIRECTLY OR INDIRECTLY) FROM SUCH ACCESS OR USE.  SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">LIMITATIONS OF LIABILITY</h4>
              <p class="terms_info">TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOU ACKNOWLEDGE AND AGREE THAT, IN NO CASE SHALL ANY COMPANY AFFILIATE’S LIABILITY TO YOU IN RESPECT TO ANY ACT OR FAILURE TO ACT IN RELATION TO THE SERVICE EXCEED THE HIGHER OF US$100 OR THE AMOUNT PAID BY YOU IN CONNECTION WITH YOUR USE OF THE SERVICE.  FURTHERMORE, IN NO CASE SHALL THE COMPANY AFFILIATES BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM PERSONAL INJURY, DAMAGE TO PROPERTY, LOSS OF PROFITS, DATA, USE, GOODWILL, BUSINESS INTERRUPTION, OR OTHER COMPARABLE LOSS) ARISING FROM YOUR ACCESS AND USE OF THE SERVICE, WHETHER BASED ON WARRANTY, PRODUCT LIABILITY, PERSONAL INJURY, CONTRACT, TORT OR ANY OTHER LEGAL THEORY AND WHETHER OR NOT THE COMPANY OR ANY COMPANY AFFILIATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE FOREGOING EXCLUSION OR THE LIMITATIONS OF LIABILITY FOR CERTAIN DAMAGES, IN SUCH JURISDICTIONS, THE COMPANY’S AND COMPANY AFFILIATES' LIABILITY SHALL BE LIMITED TO THE FULL EXTENT PERMITTED BY APPLICABLE LAW. THE COMPANY DOES NOT ENDORSE, WARRANT OR GUARANTEE ANY THIRD PARTY PRODUCT OR SERVICE OFFERED THROUGH THE SERVICE AND WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.  SPECIFICALLY, WE ARE NO LIABLE TO YOU FOR ANY DAMAGE CAUSED BY THE ACTIONS OF ANY MEDICAL PROFESSIONAL OR ANY OTHER THIRD PARTY.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">LINKS</h4>
              <p class="terms_info">For the convenience of our user, the Service may provide certain links to other products, applications, services and websites provided by third parties. The Company is not responsible for the content of any other products, applications, services or websites linked to or from the Service.  If you follow any such links, you leave the Service and you do so entirely at your own risk.  The Company provides links from the Service solely as a convenience to you and in no way should this be interpreted as a referral or endorsement of any content, sponsor or owner of any other products, applications, services and/or websites. THE COMPANY DISCLAIMS ALL WARRANTIES, RESPONSIBILITIES, LIABILILITES, CONDITIONS OR OTHER TERMS EXPRESS OR IMPLIED AS TO ANY SUCH LINKED PRODUCTS,  APPLICATIONS, SERVICES  OR WEBSITE, INCLUDING, WITHOUT LIMITATION, AS TO ACCURACY, OWNERSHIP, VALIDITY OR LEGALITY OF ANY CONTENT OF A LINKED PRODUCT, APPLICATION, SERVICE OR WEBSITE, AND FOR ANY OF YOUR INFORMATION COLLECTED OR USED BY ANY SUCH THIRD PARTIES. </p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;INDEMNIFICATION/RELEASE</h4>
              <p class="terms_info">To the maximum extent permitted by law, you agree to defend, indemnify and hold harmless any and all Company Affiliates from all claims for liabilities, losses and expenses, including reasonable attorneys' fees and costs, arising from: (a) any breach of these TOS, the Privacy Policy, Additional Terms or any applicable rules, laws or regulations, whether or not referenced herein, (b) in connection with your access and use of the Service, (c) violation of any rights of any third party or (d) communication spread by means of the Service.  The Company reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you.  The obligations set forth herein shall survive termination of these TOS. </p>
              <p class="terms_info">You are solely responsible for your interactions with other users of the Service.  If you have a dispute with one or more users of the Service, in addition to any other remedies reserved for the Company herein, you release each Company Affiliate from claims, demands and damages (actual and consequential) of every kind and nature, known or unknown, arising out of or in connection with such disputes.  If you are a California resident, you waive the rights afforded to you under California Civil Code §1542.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;GOVERNING LAW</h4>
              <p class="terms_info">The Service is made accessible, operated and controlled from Pegara, Inc. in the United States.  It can be accessed from various countries of the world.  The laws of the State of California and the United States of America, without regard to conflicts of law provisions, will apply to all matters arising out of or in connection with the Service and your access and use thereof.  By accessing and using the Service, you submit and consent to the exclusive jurisdiction of state and federal courts located in the State of California with respect to any dispute or cause of action (whether contractual or non-contractual) arising out of or in connection with these TOS, the Privacy Policy, Additional Terms and/or your access and use of the Service.  In any action or proceeding to enforce the rights under these Terms, the prevailing party shall be entitled to recover their reasonable attorneys’ fees and costs.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;INJUNCTIVE RELIEF</h4>
              <p class="terms_info">You acknowledge that the rights granted and obligations made hereunder to the Company are of a unique and irreplaceable nature, the loss of which shall irreparably harm the Company and which cannot be replaced by monetary damages alone so that the Company shall be entitled to injunctive or other equitably relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you.  To the fullest extent permitted under applicable law, you irrevocably waive all rights to seek injunctive or other equitable relief and agree to limit your claims to claims for money damages (if any). </p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;VOID WHERE PROHIBITED</h4>
              <p class="terms_info">The information provided through the Service are not intended for distribution to or use by any person in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject the Company to any registration requirement within such jurisdiction or country.  The Company makes no representation or warranty that any material in the Service is lawful in every jurisdiction from which such content can be accessed, or is available for use in all jurisdictions.  If you access or use the Service from a jurisdiction outside the State of California you are responsible for compliance with all applicable local laws.  THE SERVICE IS INTENDED FOR USE BY PERSONS AGE 18 OR OLDER.  BY ACCESSING AND USING THE SERVICE, YOU REPRESENT AND WARRANT THAT YOU ARE 18 OR OLDER, AND THAT YOU AGREE TO AND TO ABIDE BY ALL OF THE TERMS AND CONDITIONS OF THESE TOS, THE PRIVACY POLICY AND ADDITIONAL TERMS.  IF YOU ARE UNDER THE AGE OF 18, THE COMPANY MAY IMMEDIATELY (WITHOUT NOTICE) TERMINATE THE LICENSES GRANTED HEREUNDER AND CANCEL YOUR ACCOUNT AND/OR YOUR ACCESS TO THE SERVICE.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;COMPLAINTS, NOTICE AND CONTACT INFORMATION</h4>
              <p class="terms_info">The Company takes claims of infringement of intellectual property rights and violation of rights including rights of privacy or publicity very seriously.  If you believe that any of the material that is or was in the Service infringes or has infringed any rights, including copyrights or trademarks, owned by you, or by an owner for which you are authorized to act, please email us at <a href="mailto:support@pegara.com" class="block__footer__link describe__link">support@pegara.com.</a></p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;PRIVACY POLICY</h4>
              <p class="terms_info">The Company is committed to respecting your privacy and the confidentiality of your personal information.  The Privacy Policy sets out how the Company may collect, use, share and store your personal information.  If you object to your personal information being used in the way set out in the Privacy Policy, you should not access or use the Site or Service.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;NOTICE</h4>
              <p class="terms_info">In the event the Company decides, in its sole and absolute discretion, to give notice to a user regarding the termination of the licenses granted herein, revisions to payment policies, or any Changes, it may do so via email, telephone call, posting in the Service or these TOS, or such other method of notice the Company deems appropriate.  Where Company decides to give such electronic notice, you agree that all communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.  Moreover, your access or use of the Service after delivery of such notice constitutes acceptance by you of the noticed action.  </p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;RESTRICTIONS</h4>
              <p class="terms_info">The Service may be subject to international rules that govern the export of software. You shall comply with all applicable international and national laws that apply to the Service as well as end-user, end-use and destination restrictions issued by national governments.  The Company is making the Service available to you on the condition that you certify that the use of the Service is not otherwise in violation of any applicable export control and sanctions regulations. </p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;LANGUAGE</h4>
              <p class="terms_info">The parties hereto confirm their express wish that these TOS as well as all other documents related to them, including notices, be drawn up in the English language only and declare themselves satisfied therewith.</p>
            </li>
            <li class="list__detail_item">
              <h4 class="item_title">&nbsp;&nbsp;&nbsp;MISCELLANEOUS</h4>
              <p class="terms_info">If any provision of these TOS, the Privacy Policy and/or Additional Terms (if applicable) is held to be invalid or unenforceable, that provision will be deemed to be restated to reflect as nearly as possible the original intention in accordance with applicable law, and the remainder of the TOS, the Privacy Policy and/or Additional Terms will remain in full force and effect.  The TOS, the Privacy Policy and Additional Terms (if applicable) constitute the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter.  Nothing in the foregoing sentence shall exclude or restrict the liability of you arising out of fraud or fraudulent misrepresentation.  Any waiver of any provision of the TOS will be effective only if in writing and signed by the Company.  The failure of either party to assert any right under these TOS shall not be considered a waiver of that party's right will remain in full force and effect.  In addition, the TOS, the Privacy Policy and any Additional Terms, including the Company’s enforcement of those policies, are not intended to confer, and do not confer, any rights or remedies upon any person.  The original English version of these TOS may have been translated into other languages.  In the event of inconsistency or discrepancy between the English version and any other language version, the English language version shall prevail.  You are not allowed to assign the TOS or any rights hereunder.  The Company is allowed at its sole discretion to assign the TOS or any rights hereunder to any third party, without giving prior notice to you.  Our licensors may be entitled to enforce these Terms.  There are no other third party beneficiaries to these Terms.</p>
            </li>
          </ul>
          <p class="terms_info" style="text-align: center">*&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;*</p>
          <p class="terms_info">If you have any questions, complaints, or comments regarding these TOS, or have other questions or suggestions about the Service, please email us at <a href="mailto:support@pegara.com" class="block__footer__link describe__link">support@pegara.com</a>.</p>
          <p class="terms_info">© 2016 Pegara, Inc.  All rights reserved.  </p>
          <br>
        </div>

        <div class="terms_content">
          <h3 class="page_title">SUPPLEMENTAL TERMS OF SERVICE<br>FOR BRAINSALVATION DIETARY PROGRAM</h3>
          <p>(Effective Date: November 07, 2016)</p>		  
<p class="terms_info">
These Supplemental Terms of Service (“Supplemental Terms”) for brainsalvation Dietary Service Program (“Program”) are an addendum to the Pegara Terms of Service (“TOS”), and apply to customer’s use and subscription to the Program.   Services other than the Program remain subject to the TOS and any terms and conditions referenced therein.  In the case of any conflict between these Supplemental Terms and the terms and conditions of the TOS that are not expressly resolved by their terms, these Supplemental Terms control.
</p>
<p class="terms_info">
Dietary Service Program.  Through the Program, we delivery certain nutritional, dietary and health-related feedback and information services via the Site(s), Company-designed health coaches (each, a “Coach”) and other processes.  We will designate a Coach for you based in part on background information, including, dietary information, personal information, physical activity level, Risk Reduction Score, Memory Performance Index result and photos, you may provide to us.  While we may monitor the quality of provision of Services provide your Coach to you, you should be aware that we make no representations about the suitability, quality, availability, timeliness or accuracy of the feedback and information delivered by your Coach.  You may, however, contact us at any time to provide feedback regarding your Coach and/or to request a new Coach to be assigned to you.  We reserve the right to change your Coach at any time in our sole discretion.   We will, however, endeavor to provide reasonable advance notice where possible. 
</p>
<p class="terms_info">
Eligibility.   We do not permit individual under 21 years of age, over 65 years of age, or who are not residents of the United States to become registered users of the Program.  Moreover, those individuals who fall within the following categories may not register for the Program: (a) diagnosed and receiving treatment for Alzheimer’s disease, or (b) have allergies to any of the following: olive oil, whole grains, berries, vegetables (including beans or leafy greens), poultry, fish, wine or nuts, (c) diagnosed with cardiovascular conditions such as congestive heart disease, coronary artery disease, (d) have a history of heart attack or stroke (e) suffered heart or kidney failure and taking medication, (f) receiving dialysis or cancer treatment (g) other health conditions.  By accessing and using the Program, you represent and warrant that you are at least 21 years of age, 65 years of age or younger, and a resident of the United States.  Moreover, you represent and warranty that you do not fall within any of the foregoing health condition categories.
</p>
<p class="terms_info">
Method of Communication.   As more particularly described in the applicable Site, communication between you and your Coach will be through skype, telephone, SMS/MMS, email, in-mobile app communication tools and/or such other mode of communication authorized from time to time by the Company.
</p>
<p class="terms_info">
Paid Subscriptions.  As more particularly described in the applicable Site, you may elect to subscribe for a premium paid subscription service in the Program.  The components, content, features, functionality, resources, and access to Coaches will vary depending on the type of subscription service you elect and your payment of all applicable fees.  You may cancel a premium paid subscription service by contacting us at <a href="mailto:support@pegara.com" class="block__footer__link describe__link">support@pegara.com</a>; provided, however, if you cancel your premium paid subscription service, your subscription will remain active (and you will be responsible for payment of applicable subscription fees) through the end of the then-current subscription period.
</p>
<p class="terms_info">
Auto Renewals.  Except as otherwise provide in the Site, the TOS or these Supplemental Terms,  or with your cancelation prior the subject subscription expiration date, your subscription will automatically extend for one (1) month periods following the expiration of the original subscription term selected at the then applicable non-promotional subscription rate.   
</p>
          <p class="terms_info" style="text-align: center">*&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;*</p>
          <p class="terms_info">If you have any questions, complaints, or comments regarding these TOS, or have other questions or suggestions about the Service, please email us at <a href="mailto:support@pegara.com" class="block__footer__link describe__link">support@pegara.com</a>.</p>
          <p class="terms_info">© 2016 Pegara, Inc.  All rights reserved.  </p>
          <div class="btn_home">
            <a href="{{ URL::previous() }}" class="btn btn-block btn__regular long">Go to Previous Page</a>
          </div>
          <br>
		  
		  
		</div>
		
      </div>
    </div>
@stop
